"""
Repository Traceability:
- Source Document: DI-SPRINT-01 (Required Audit Events), DI-0015 (Audit and Traceability).
- Purpose: Stable audit-event action codes for Sprint 01 inspection and evidence flow.
"""


class AuditAction:
    # Auth (Sprint 00)
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGIN_BLOCKED = "AUTH_LOGIN_BLOCKED"
    AUTH_LOGIN_DISABLED = "AUTH_LOGIN_DISABLED"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    # Inspection lifecycle (Sprint 01)
    INSPECTION_CREATED = "INSPECTION_CREATED"
    INSPECTION_VIEWED = "INSPECTION_VIEWED"
    INSPECTION_LISTED = "INSPECTION_LISTED"
    INSPECTION_SUBMITTED = "INSPECTION_SUBMITTED"
    INSPECTION_STATUS_CHANGED = "INSPECTION_STATUS_CHANGED"
    INSPECTION_CANCELLED = "INSPECTION_CANCELLED"
    INSPECTION_FAILED = "INSPECTION_FAILED"

    # Image + evidence (Sprint 01)
    IMAGE_UPLOAD_REQUESTED = "IMAGE_UPLOAD_REQUESTED"
    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    IMAGE_REGISTERED = "IMAGE_REGISTERED"
    IMAGE_REGISTRATION_REJECTED = "IMAGE_REGISTRATION_REJECTED"
    EVIDENCE_ACCESS_LINK_CREATED = "EVIDENCE_ACCESS_LINK_CREATED"
    EVIDENCE_ACCESS_DENIED = "EVIDENCE_ACCESS_DENIED"

    # Security
    UNAUTHORIZED_ACCESS_ATTEMPT = "UNAUTHORIZED_ACCESS_ATTEMPT"
    TENANT_SCOPE_VIOLATION = "TENANT_SCOPE_VIOLATION"


class ActorType:
    USER = "USER"
    SERVICE = "SERVICE"
    SYSTEM = "SYSTEM"


class ObjectType:
    AUTH = "AUTH"
    INSPECTION_SESSION = "INSPECTION_SESSION"
    INSPECTION_IMAGE = "INSPECTION_IMAGE"
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    UPLOAD_REQUEST = "UPLOAD_REQUEST"
