"""
Repository Traceability:
- Source Document: DI-SPRINT-01 (Required Audit Events), DI-0015 (Audit and Traceability).
- Purpose: Stable audit-event action codes for Sprint 01 inspection and evidence flow.
"""


class AuditAction:
    # Auth (Sprint 00)
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGIN_BLOCKED = "AUTH_LOGIN_BLOCKED"
    AUTH_LOGIN_DISABLED = "AUTH_LOGIN_DISABLED"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    # Inspection lifecycle (Sprint 01)
    INSPECTION_CREATED = "INSPECTION_CREATED"
    INSPECTION_VIEWED = "INSPECTION_VIEWED"
    INSPECTION_LISTED = "INSPECTION_LISTED"
    INSPECTION_SUBMITTED = "INSPECTION_SUBMITTED"
    INSPECTION_STATUS_CHANGED = "INSPECTION_STATUS_CHANGED"
    INSPECTION_CANCELLED = "INSPECTION_CANCELLED"
    INSPECTION_FAILED = "INSPECTION_FAILED"

    # Image + evidence (Sprint 01)
    IMAGE_UPLOAD_REQUESTED = "IMAGE_UPLOAD_REQUESTED"
    IMAGE_UPLOADED = "IMAGE_UPLOADED"
    IMAGE_REGISTERED = "IMAGE_REGISTERED"
    IMAGE_REGISTRATION_REJECTED = "IMAGE_REGISTRATION_REJECTED"
    EVIDENCE_ACCESS_LINK_CREATED = "EVIDENCE_ACCESS_LINK_CREATED"
    EVIDENCE_ACCESS_DENIED = "EVIDENCE_ACCESS_DENIED"

    # AI advisory (Sprint 02)
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"
    AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED"

    # Comparison (Sprint 03)
    DAMAGE_COMPARISON_REQUESTED = "DAMAGE_COMPARISON_REQUESTED"
    DAMAGE_COMPARISON_COMPLETED = "DAMAGE_COMPARISON_COMPLETED"
    DAMAGE_COMPARISON_FAILED = "DAMAGE_COMPARISON_FAILED"
    COMPARISON_NOT_COMPARABLE = "COMPARISON_NOT_COMPARABLE"

    # Review (Sprint 03)
    REVIEW_ITEM_CREATED = "REVIEW_ITEM_CREATED"
    REVIEW_ITEM_VIEWED = "REVIEW_ITEM_VIEWED"
    REVIEW_DECISION_RECORDED = "REVIEW_DECISION_RECORDED"
    REVIEW_ITEM_ESCALATED = "REVIEW_ITEM_ESCALATED"
    ADDITIONAL_EVIDENCE_REQUESTED = "ADDITIONAL_EVIDENCE_REQUESTED"

    # Damage cases (Sprint 03)
    DAMAGE_CASE_CREATED = "DAMAGE_CASE_CREATED"
    DAMAGE_CASE_VIEWED = "DAMAGE_CASE_VIEWED"
    DAMAGE_CASE_STATUS_CHANGED = "DAMAGE_CASE_STATUS_CHANGED"
    DAMAGE_CASE_LINK_UPDATED = "DAMAGE_CASE_LINK_UPDATED"
    DUPLICATE_DAMAGE_CASE_PREVENTED = "DUPLICATE_DAMAGE_CASE_PREVENTED"

    # Per-vehicle evidence strip (DI-0037)
    PER_VEHICLE_STRIP_VIEWED = "PER_VEHICLE_STRIP_VIEWED"

    # Reports + evidence packages (Sprint 05)
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"
    REPORT_VIEWED = "REPORT_VIEWED"
    REPORT_ACCESS_LINK_CREATED = "REPORT_ACCESS_LINK_CREATED"
    EVIDENCE_PACKAGE_GENERATED = "EVIDENCE_PACKAGE_GENERATED"

    # Integration — CROMS + Maintenance (Sprint 04)
    CROMS_CHECKOUT_INSPECTION_REQUESTED = "CROMS_CHECKOUT_INSPECTION_REQUESTED"
    CROMS_CHECKIN_INSPECTION_REQUESTED = "CROMS_CHECKIN_INSPECTION_REQUESTED"
    CROMS_DAMAGE_SUMMARY_ACCESSED = "CROMS_DAMAGE_SUMMARY_ACCESSED"
    CROMS_INSPECTION_STATUS_ACCESSED = "CROMS_INSPECTION_STATUS_ACCESSED"
    CROMS_NOTIFICATION_QUEUED = "CROMS_NOTIFICATION_QUEUED"
    MAINTENANCE_HANDOFF_REQUESTED = "MAINTENANCE_HANDOFF_REQUESTED"
    MAINTENANCE_WORK_ORDER_REFERENCE_RECEIVED = "MAINTENANCE_WORK_ORDER_REFERENCE_RECEIVED"
    MAINTENANCE_REPAIR_STATUS_RECEIVED = "MAINTENANCE_REPAIR_STATUS_RECEIVED"
    MAINTENANCE_REJECTION_RECEIVED = "MAINTENANCE_REJECTION_RECEIVED"
    MAINTENANCE_ADDITIONAL_EVIDENCE_REQUESTED = "MAINTENANCE_ADDITIONAL_EVIDENCE_REQUESTED"
    INTEGRATION_RETRY_SCHEDULED = "INTEGRATION_RETRY_SCHEDULED"
    INTEGRATION_FAILED = "INTEGRATION_FAILED"
    INTEGRATION_DEAD_LETTERED = "INTEGRATION_DEAD_LETTERED"
    IDEMPOTENCY_CONFLICT_DETECTED = "IDEMPOTENCY_CONFLICT_DETECTED"

    # Security
    UNAUTHORIZED_ACCESS_ATTEMPT = "UNAUTHORIZED_ACCESS_ATTEMPT"
    TENANT_SCOPE_VIOLATION = "TENANT_SCOPE_VIOLATION"


class ActorType:
    USER = "USER"
    SERVICE = "SERVICE"
    SYSTEM = "SYSTEM"


class ObjectType:
    AUTH = "AUTH"
    INSPECTION_SESSION = "INSPECTION_SESSION"
    INSPECTION_IMAGE = "INSPECTION_IMAGE"
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    UPLOAD_REQUEST = "UPLOAD_REQUEST"
    AI_ANALYSIS = "AI_ANALYSIS"
    DAMAGE_COMPARISON = "DAMAGE_COMPARISON"
    REVIEW_ITEM = "REVIEW_ITEM"
    DAMAGE_CASE = "DAMAGE_CASE"
    INTEGRATION = "INTEGRATION"
    MAINTENANCE_HANDOFF = "MAINTENANCE_HANDOFF"
    REPORT = "REPORT"
