"""
Repository Traceability:
- Source Document: DI-0034 (Standard Error Codes table)
- Purpose: Stable error code constants for the safe error envelope.
"""


class ErrorCode:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    TENANT_SCOPE_VIOLATION = "TENANT_SCOPE_VIOLATION"
    CONFLICT = "CONFLICT"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    AI_PROCESSING_FAILED = "AI_PROCESSING_FAILED"
    INTEGRATION_FAILED = "INTEGRATION_FAILED"
    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
