"""
Repository Traceability:
- Purpose: One-click demo data seeder for stakeholder walkthroughs on the deployed URL.
  Runs a full advisory flow end-to-end: inspection -> evidence -> AI -> comparison ->
  damage case -> evidence-package report. Tenant-scoped, audited via the underlying services.
- Not part of the core product contract (operator convenience). Honors all ownership boundaries.
"""
from __future__ import annotations

import base64
import uuid
from datetime import datetime, timezone

from bson import ObjectId

from application.ai.damage_detection_service import run_analysis_for_session
from application.services import comparison_service, damage_case_service, image_service, report_service
from application.services.inspection_service import _load_session_for_tenant, create_inspection_session
from infrastructure.db.mongo import get_db
from infrastructure.storage.local_storage import storage_root

# Minimal valid 1x1 white JPEG so AI/storage accept a real (if trivial) image.
_DEMO_JPEG = base64.b64decode(
    "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAP//////////////////////////////////////"
    "////////////////////////////////////////////////////wgARCAABAAEDASIAAhEB"
    "AxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhAD"
    "EAAAAB//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABBQJ//8QAFBEBAAAAAAAAAAAAAAAA"
    "AAAAAP/aAAgBAwEBPwF//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//8QAFBABAAAA"
    "AAAAAAAAAAAAAAAAAP/aAAgBAQAGPwJ//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPyF/"
    "/9oADAMBAAIAAwAAABCQ//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPxB//8QAFBEBAAAA"
    "AAAAAAAAAAAAAAAAAP/aAAgBAgEBPxB//8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxB/"
    "/9k="
)


def _now() -> datetime:
    return datetime.now(timezone.utc)


async def seed_demo(*, principal: dict, correlation_id: str) -> dict:
    db = get_db()
    tenant_id = principal["tenantId"]
    suffix = uuid.uuid4().hex[:6].upper()

    session = await create_inspection_session(
        principal=principal,
        payload={
            "inspectionType": "CHECK_IN", "sourceSystem": "DI-Web",
            "references": {"externalVehicleRef": f"DEMO-VEH-{suffix}",
                           "externalRentalAgreementRef": f"DEMO-RA-{suffix}"},
        },
        correlation_id=correlation_id,
    )
    session_id = session["id"]

    # Upload + register a demo image (server-side equivalent of the signed PUT flow).
    ur = await image_service.create_upload_request(
        principal=principal, session_id=session_id, capture_position="CAPTURE_FRONT",
        file_name="demo-front.jpg", content_type="image/jpeg", file_size=len(_DEMO_JPEG),
        correlation_id=correlation_id,
    )
    target = storage_root() / ur["objectPath"] if ur.get("objectPath") else None
    if target is None:
        # objectPath is internal to the upload-request record; fetch it.
        rec = await db.di_upload_requests.find_one({"_id": ObjectId(ur["uploadRequestId"])})
        target = storage_root() / rec["objectPath"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(_DEMO_JPEG)
    await db.di_upload_requests.update_one(
        {"_id": ObjectId(ur["uploadRequestId"]), "tenantId": tenant_id},
        {"$set": {"status": "UPLOADED", "uploadedAt": _now(), "uploadedFileSize": len(_DEMO_JPEG)}},
    )
    await image_service.register_uploaded_image(
        principal=principal, session_id=session_id, upload_request_id=ur["uploadRequestId"],
        correlation_id=correlation_id,
    )

    # Advisory AI analysis (real Gemini; demo image may yield no findings — that's fine).
    session_doc = await _load_session_for_tenant(tenant_id=tenant_id, session_id=session_id)
    ai = await run_analysis_for_session(principal=principal, session=session_doc, correlation_id=correlation_id)

    # Comparison: no prior baseline -> NOT_COMPARABLE (fast, deterministic) + a comparison result.
    comparison = await comparison_service.request_comparison(
        principal=principal, session_id=session_id, baseline_inspection_session_id=None,
        comparison_profile_code=None, route_uncertain_to_review=True, correlation_id=correlation_id,
    )
    result_id = comparison["outcomes"][0]["comparisonResultId"] if comparison.get("outcomes") else None

    case = None
    if result_id:
        case = await damage_case_service.create_case(
            principal=principal, inspection_session_id=session_id, damage_finding_ids=[],
            comparison_result_ids=[result_id], case_type="REPAIR_RELEVANT", severity_code="MEDIUM",
            description="Demo damage case generated by the one-click seeder.",
            correlation_id=correlation_id,
        )

    report = await report_service.generate_report(
        principal=principal, report_type="EVIDENCE_PACKAGE_REPORT",
        refs={"inspectionSessionId": session_id}, fmt="JSON", locale="en", correlation_id=correlation_id,
    )

    return {
        "inspectionSessionId": session_id,
        "aiAnalysisId": ai.get("id"),
        "aiFindings": ai.get("totalFindings"),
        "reviewItemsRouted": (ai.get("reviewItemsRouted") or 0) + (comparison.get("reviewItemsRouted") or 0),
        "comparisonId": comparison.get("comparisonId"),
        "comparisonStatus": comparison.get("status"),
        "damageCaseId": case["damageCaseId"] if case else None,
        "reportId": report.get("reportId"),
        "message": "Demo data created. Open Inspections / Review Queue / Damage Cases / Reports to explore.",
    }
